### ISSUE TITLE
Rewrite in Node or Go or something

### ISSUE THREAD

**Issue by mattdsteele** [mattdsteele/particle-action#1]
Have to install curl to do it via a Bash script which is a bummer

**Comment by mattdsteele** [comment]
Also stop using debian slim in replacement of Alpine or something similar

**Comment by mattdsteele** [comment]
@jmhobbs I'm calling you in!

I want to write a super simple Go program that makes an HTTP call, and deploy it as a Docker container. Is this a good approach (compile the executable locally, and put it into a tiny Alpine container)?

https://fabianlee.org/2018/05/10/docker-packaging-a-golang-version-of-hello-world-in-a-container/

**Comment by jmhobbs** [comment]
For sure.  You don't even need Alpine, just use scratch, and if you need the SSL support copy over those files from the golang builder container.

**Comment by mattdsteele** [comment]
Done! Went from a 90MB image to 5MB; neat :)

Is this a pretty well known pattern @jmhobbs? I could do a lightning talk about this at the next meetup...

**Comment by jmhobbs** [comment]
It's a pretty standard trick, but worth a short talk for sure!
